added side bar and navbar to admin ui resolves #11
Scott-Coates-Org/group-project-team-green pull request #16
Opened 2022-06-25 19:11 UTC by amarborz

2022-06-26 18:20 UTC, BerkeKaragoz requested changes
This is generated by `npm` commands. Our project uses `yarn`. So this shouldn't be generated or pushed.
Install: `yarn` = `npm i`
Run as dev: `yarn dev` = `npm run dev`

2022-06-26 18:27 UTC, BerkeKaragoz requested changes
# package-lock.json
`package-lock.json` is generated by `npm` commands. Our project uses `yarn`. So this shouldn't be generated or pushed.
Install: `yarn` = `npm i`
Run as dev: `yarn dev` = `npm run dev`
# .vscode/extensions.json
Lets not delete this one and make it smaller instead. Just leave it as is for now.
# .gitignore
Lets not ignore `.vscode`. I can submit a minimalistic one ?
# src/components/admin/sideBar/SideBar.jsx
`key` prop should be on the root element which is at the 16th row instead of 20th. That resolves the key error.

2022-06-27 19:34 UTC, ematkinsongit approved these changes
approved to resolve #11 
 approved for merge

2022-06-28 16:50 UTC, BerkeKaragoz approved these changes

2022-06-28 16:51 UTC, merged